/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hakuna_matata;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author NNAMDI
 */
//Controller class relying on model class hakuna
public class matata extends javax.swing.JFrame {

    static enrollment_module_panel enroll;
    static raising_module_panel raise;
    static gate_module_panel gate;
    static security_module_panel security;
    static approval_module_panel approve;
    static matata display;
    static hakuna hakunas;

    /**
     * Creates new form matata
     */
    public matata() {
        //initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // To initialize enroll
    public static void initialize_enroll() {
        enroll = new enrollment_module_panel();
        hakunas = new hakuna();

        hakunas.set_enrollment_name(enroll);
        hakunas.set_designation_name(enroll);
        hakunas.set_fingerprint(enroll);
        hakunas.set_photo(enroll);
        hakunas.set_id_number(enroll);

        //For save button of enrollment_module
        enroll.jButton1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                String name = hakunas.get_enrollment_name(enroll); // Continue from here
                String designation = hakunas.get_designation_name(enroll);
                String fingerprint = hakunas.get_fingerprint(enroll);
                String photo = hakunas.get_photo(enroll);
                String id_number = hakunas.get_id_number(enroll);

                hakuna.insert_value_enroll(designation, fingerprint, photo, id_number, name, enroll);
                System.out.println("Wilson " + name);
                JOptionPane.showMessageDialog(enroll, "Data enrolled for " + name + "  " + designation + " successfully");
            }
        });

        //For cancel button of enrollment_module
        enroll.jButton2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                System.out.println("Cancel");
                System.exit(0);
            }
        });
    }// End of initialize enroll

    // To initialize raising  raising_initialize
    public static void initialize_raising() {
        raise = new raising_module_panel();
        hakunas = new hakuna();

        hakunas.set_raise_name_of_visitor(raise);
        hakunas.set_raise_name_of_raisee(raise);
        hakunas.set_raise_from_where(raise);
        hakunas.set_raise_to_see_whom(raise);
        hakunas.set_raise_id_number_of_raisee(raise);

        //For raise button of raising_module
        raise.jButton1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                String name = hakunas.get_raise_name_of_visitor(raise); // Continue from here
                String name_of_raisee = hakunas.get_raise_name_of_raisee(raise);
                String from_where = hakunas.get_raise_from_where(raise);
                String to_see_whom = hakunas.get_raise_to_see_whom(raise);
                String id_number = hakunas.get_raise_id_number_of_raisee(raise);
                String visitor_a_former_employee = hakunas.get_raise_is_a_visitor_a_former_employee(raise);
                String purpose_of_visit = hakunas.get_raise_purpose_of_visit(raise);
                String date_of_intended_visit = hakunas.get_raise_date_of_intended_visit(raise);
                String pass_type = hakunas.get_raise_pass_type(raise);
                String approver = hakunas.get_raise_approver(raise);
                String status = "Pending";
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy ");
                Date date = new Date();

                String date_raised = df.format(date);
                System.out.println("Approver " + approver);

                hakuna.insert_value_raise(name, name_of_raisee, from_where, to_see_whom, id_number, visitor_a_former_employee,
                        purpose_of_visit, date_of_intended_visit, pass_type, approver, raise, date_raised, status);

                System.out.println("Wilson " + name);

            }
        });

        //For cancel button of enrollment_module
        raise.jButton2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                System.out.println("Cancel");
                System.exit(0);
            }
        });

        matata displaysg = new matata();
        displaysg.add(raise); // Always change to the appropriate type be it security, approve, enroll, gate, raise.
        displaysg.setSize(960, 455);
        displaysg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        displaysg.setVisible(true);

    }// End of initialize raising module

    //Initialize approver
    public static void initialize_approver(String approver) {
        approve = new approval_module_panel();
        hakunas = new hakuna();

        hakunas.load_table(approve, approver);

        //For cancel button of enrollment_module
        approve.jButton1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                System.out.println("Cancel");
                System.exit(0);
            }
        });

        // Reload table
        approve.jButton2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                hakunas.reload_table(approve, approver);
            }
        });

        matata displaysf = new matata();
        displaysf.add(approve); // Always change to the appropriate type be it security, approve, enroll, gate, raise.
        displaysf.setSize(960, 455);
        displaysf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        displaysf.setVisible(true);
    }
    //End of initialize approver

    // Beginning of initialize security
    public static void initialize_security() {
        security = new security_module_panel();
        hakunas = new hakuna();

        hakunas.populate_table_security(security);

        //For cancel button of enrollment_module
        security.jButton1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                System.out.println("Cancel");
                System.exit(0);
            }
        });

        matata displaysd = new matata();
        displaysd.add(security); // Always change to the appropriate type be it security, approve, enroll, gate, raise.
        displaysd.setSize(960, 455);
        displaysd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        displaysd.setVisible(true);

    }
    //End of initialize security

    // Beginning of initialize gate
    public static void initialize_gate() {
        gate = new gate_module_panel();
        hakunas = new hakuna();
        hakunas.load_gate_table(gate);
        matata displayss = new matata();
        displayss.add(gate); // Always change to the appropriate type be it security, approve, enroll, gate, raise.
        displayss.setSize(960, 455);
        displayss.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        displayss.setVisible(true);

    }
    //End of initialize gate

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //initialize_enroll(); // use to enroll staff
        initialize_raising();
        // Upon installation,install the appropriate initialize_approver for ED, MD
        initialize_approver("ED");// Takes the user eg Ed, MD, AGM as a function to generate their approval table
       initialize_security();
        initialize_gate();
        // Continue from here for security

         display = new matata();
        display.add(enroll); // Always change to the appropriate type be it security, approve, enroll, gate, raise.
        display.setSize(960, 455);
        display.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        display.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
